# Generated by Django 3.0.7 on 2020-07-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='used_letters',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='word',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='game',
            name='lives',
            field=models.IntegerField(default=6),
        ),
    ]
