# Generated by Django 3.0.7 on 2020-07-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_game', '0003_auto_20200720_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='word_letters',
        ),
        migrations.AddField(
            model_name='game',
            name='word_letters_count',
            field=models.IntegerField(default=0),
        ),
    ]
